
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '9.0'

# ignore all warnings from all pods
inhibit_all_warnings!
use_frameworks!

def common_pods
    pod 'BFPaperButton'
end

target 'Challenge2' do

    common_pods

end
